apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-docker-registry-web-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.1.201:6789
      - 172.16.1.202:6789
      - 172.16.1.203:6789
    path: /docker-registry/web-data
    secretRef:
      name: ceph-key
      namespace: system-homeprod
    user: admin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-docker-registry-web-config
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.1.201:6789
      - 172.16.1.202:6789
      - 172.16.1.203:6789
    path: /docker-registry/web-config
    secretRef:
      name: ceph-key
      namespace: system-homeprod
    user: admin
---