apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infrastructure
  name: docker-registry-web-data
  labels:
    app: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: ceph-docker-registry-web-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infrastructure
  name: docker-registry-web-config
  labels:
    app: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: ceph-docker-registry-web-config
---