apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-docker-registry-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.1.201:6789
      - 172.16.1.202:6789
      - 172.16.1.203:6789
    path: /docker-registry/app-data
    secretRef:
      name: ceph-key
      namespace: system-homeprod
    user: admin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-docker-registry-config
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.1.201:6789
      - 172.16.1.202:6789
      - 172.16.1.203:6789
    path: /docker-registry/app-config
    secretRef:
      name: ceph-key
      namespace: system-homeprod
    user: admin
---